Repository WoowonKim/TheBeauty, pull requests merged in 2023-06, with the labels that each got.

#153 merge issue#145
  THEBeautySpring/src/main/java/com/kosa/theBeauty/cart/controller/CartController.java
  THEBeautySpring/src/main/java/com/kosa/theBeauty/cart/dao/CartDAO.java
  THEBeautySpring/src/main/java/com/kosa/theBeauty/cart/service/CartService.java
  THEBeautySpring/src/main/java/com/kosa/theBeauty/cart/service/CartServiceImpl.java
  THEBeautySpring/src/main/java/com/kosa/theBeauty/main/controller/MainController.java
  THEBeautySpring/src/main/java/com/kosa/theBeauty/main/dao/mainDAO.java
  THEBeautySpring/src/main/java/com/kosa/theBeauty/main/service/MainServiceImpl.java
  THEBeautySpring/src/main/java/com/kosa/theBeauty/main/service/mainService.java
  THEBeautySpring/src/main/java/com/kosa/theBeauty/openvido/consult/ConsultController.java
  THEBeautySpring/src/main/java/com/kosa/theBeauty/reservation/controller/reserveController.java
  THEBeautySpring/src/main/java/com/kosa/theBeauty/reservation/service/reserveService.java
  THEBeautySpring/src/main/java/com/kosa/theBeauty/survey/controller/SurveyController.java
  THEBeautySpring/src/main/resources/mappers/brandMapper.xml
  THEBeautySpring/src/main/resources/mappers/cartMapper.xml
Labels: 메인페이지, 장바구니

#154 merge #150
  THEBeautySpring/src/main/webapp/WEB-INF/views/product/categoryProduct.jsp
  THEBeautySpring/src/main/webapp/WEB-INF/views/product/productDetail.jsp
  THEBeautySpring/src/main/webapp/WEB-INF/views/product/productSearchResult.jsp
  THEBeautySpring/src/main/webapp/WEB-INF/views/reservation/adminReservation.jsp
  THEBeautySpring/src/main/webapp/WEB-INF/views/user/findEmail.jsp
  THEBeautySpring/src/main/webapp/WEB-INF/views/user/findEmailResult.jsp
  THEBeautySpring/src/main/webapp/resources/js/cart/cartPage.js
  THEBeautySpring/src/main/webapp/resources/js/main/brand.js
  THEBeautySpring/src/main/webapp/resources/js/product/pagination.js
  THEBeautySpring/src/main/webapp/resources/js/product/productDetail.js
  THEBeautySpring/src/main/webapp/resources/js/product/productList.js
  THEBeautySpring/src/main/webapp/resources/js/reservation/adminPageCalendar.js
  THEBeautySpring/src/main/webapp/resources/js/reservation/calendar.js
  THEBeautySpring/src/main/webapp/resources/js/survey/survey.js
  THEBeautySpring/src/main/webapp/resources/js/user/findEmail.js
  THEBeautySpring/src/main/webapp/resources/js/user/findPw.js
  THEBeautySpring/src/main/webapp/resources/js/user/register.js
Labels: 메인페이지, 예약페이지, 관리자 페이지

#156 merge issue#155
  THEBeautySpring/src/main/webapp/WEB-INF/views/reservation/adminReservation.jsp
  THEBeautySpring/src/main/webapp/resources/js/reservation/adminPageCalendar.js
Labels: 예약관리페이지

#159 merge issue#158
  THEBeautySpring/src/main/resources/mappers/brandMapper.xml
  THEBeautySpring/src/main/resources/mappers/userMapper.xml
Labels: bug

#161 merge issue#160
  THEBeautySpring/src/main/java/com/kosa/theBeauty/reservation/controller/ReserveController.java
  THEBeautySpring/src/main/webapp/WEB-INF/views/reservation/adminReservation.jsp
  THEBeautySpring/src/main/webapp/resources/js/reservation/managingReserve.js
Labels: 예약 상세 페이지, 예약관리페이지

#162 merge issue#157
  THEBeautySpring/src/main/webapp/WEB-INF/views/header/header.jsp
  THEBeautySpring/src/main/webapp/resources/js/header/header.js
Labels: header

#164 merge issue#163
  THEBeautySpring/src/main/java/com/kosa/theBeauty/user/controller/UserController.java
  THEBeautySpring/src/main/webapp/WEB-INF/views/user/login.jsp
  THEBeautySpring/src/main/webapp/WEB-INF/views/user/register.jsp
  THEBeautySpring/src/main/webapp/resources/js/user/register.js
Labels: 로그인, 유저

#166 merge issue#165
  SQL/PLSQL.sql
  SQL/theBeauty DDL.sql
  SQL/theBeautyDummy.sql
  THEBeautySpring/src/main/java/com/kosa/theBeauty/consult/controller/ConsultController.java
  THEBeautySpring/src/main/webapp/WEB-INF/spring/datasource-context.xml
  THEBeautySpring/src/main/webapp/WEB-INF/views/consult/consult.jsp
  THEBeautySpring/src/main/webapp/resources/consult/favicon.ico
  THEBeautySpring/src/main/webapp/resources/css/consult/style.css
  THEBeautySpring/src/main/webapp/resources/js/consult/app.js
  THEBeautySpring/src/main/webapp/resources/js/consult/openvidu-browser-2.27.0.js
Labels: refactor
